"""Generate bundled demo images for the app's Pipeline Demo screen.

Takes aligned LFW faces (open dataset, no personal data), composites each onto a
neutral 256x256 canvas at a camera-like face-to-frame ratio, and emits them as a
TypeScript module of base64 raw-RGB buffers. The Pipeline Demo screen runs the
full on-device pipeline (detect -> landmarks -> align -> embed -> match) on
these frames, which is how the identical code path is demonstrated on iOS
simulators (no camera) and in deterministic Android demos.

Usage:  python scripts/make_demo_assets.py   (from ml/)
Writes: app/src/netraid/demoAssets.ts
"""

import base64
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
FACES = ROOT / "ml" / "data" / "aligned_faces.npy"
LABELS = ROOT / "ml" / "data" / "aligned_labels.npy"
OUT = ROOT / "app" / "src" / "netraid" / "demoAssets.ts"

CANVAS = 256          # emitted frame size (square, like the camera ROI path)
FACE = 164            # upscaled face size on the canvas -> fit ~0.64, well framed
BG = (96, 100, 104)   # neutral background

# (identity label used on screen, LFW label id, index within that identity)
PICKS = [
    ("Person A · shot 1", 10, 0),
    ("Person A · shot 2", 10, 40),   # a different session of the same identity
    ("Person B", 58, 0),
    ("Person C", 12, 0),
]


def composite(face_112: np.ndarray) -> Image.Image:
    img = Image.fromarray(face_112, "RGB").resize((FACE, FACE), Image.BILINEAR)
    canvas = Image.new("RGB", (CANVAS, CANVAS), BG)
    off = (CANVAS - FACE) // 2
    canvas.paste(img, (off, off))
    return canvas


def main() -> None:
    faces = np.load(FACES)
    labels = np.load(LABELS)
    png_dir = ROOT / "app" / "assets" / "demo"
    png_dir.mkdir(parents=True, exist_ok=True)
    entries = []
    for n, (label, ident, idx) in enumerate(PICKS):
        rows = np.where(labels == ident)[0]
        if idx >= len(rows):
            raise SystemExit(f"identity {ident} has only {len(rows)} images")
        canvas = composite(faces[rows[idx]])
        # The PNG is the SAME frame, for on-screen display: the jury sees the
        # exact image the models processed. The raw RGB below is what runs
        # through the pipeline.
        canvas.save(png_dir / f"demo_{n}.png")
        raw = canvas.tobytes()
        entries.append((label, f"id{ident}", n, base64.b64encode(raw).decode("ascii")))

    lines = [
        "// GENERATED by ml/scripts/make_demo_assets.py, do not edit by hand.",
        "// Aligned LFW faces (open dataset) composited onto neutral 256x256 frames.",
        "// `b64` is the raw RGB the pipeline actually processes; `image` is a PNG of",
        "// the SAME frame for on-screen display, so viewers see exactly what the",
        "// models saw. Used by the Pipeline Demo screen (iOS simulator, deterministic",
        "// demos).",
        "",
        f"export const DEMO_FRAME_SIZE = {CANVAS};",
        "",
        "export interface DemoAsset {",
        "  /** On-screen label. */ label: string;",
        "  /** Ground-truth identity key (same key = same person). */ identity: string;",
        "  /** Displayable PNG of the identical frame (require() asset id). */ image: number;",
        "  /** base64 of raw RGB (DEMO_FRAME_SIZE^2 * 3 bytes). */ b64: string;",
        "}",
        "",
        "export const DEMO_ASSETS: DemoAsset[] = [",
    ]
    for label, ident, n, b64 in entries:
        lines.append("  {")
        lines.append(f"    label: '{label}',")
        lines.append(f"    identity: '{ident}',")
        lines.append(f"    image: require('../../assets/demo/demo_{n}.png'),")
        lines.append(f"    b64:\n      '{b64}',")
        lines.append("  },")
    lines.append("];")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size / 1024:.0f} KB, {len(entries)} assets)")


if __name__ == "__main__":
    main()
